package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const version = "0.1.0"

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(0)
	}

	switch os.Args[1] {
	case "init":
		runInit()
	case "start":
		runStart()
	case "stop":
		runStop()
	case "status":
		runStatus()
	case "logs":
		service := ""
		if len(os.Args) >= 3 {
			service = os.Args[2]
		}
		runLogs(service)
	case "migrate":
		runMigrate()
	case "deploy":
		runDeploy()
	case "version", "--version", "-v":
		fmt.Println("gobase", version)
	case "help", "--help", "-h":
		printUsage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Print(`GoBase CLI ` + version + ` — open-source BaaS

Usage:
  gobase <command> [flags]

Commands:
  init        Create .env and docker-compose.yml in the current directory
  start       Start the GoBase stack (docker compose up -d)
  stop        Stop the GoBase stack (docker compose down)
  status      Show health of each running service
  logs [svc]  Tail logs for all services, or a specific one
  migrate     Run database migrations against the running stack
  deploy      Deploy to GoBase Cloud (requires GOBASE_TOKEN env var)
  version     Print version

Examples:
  gobase init
  gobase start
  gobase status
  gobase logs auth
  gobase migrate
`)
}

// ── init ──────────────────────────────────────────────────────────────────────

const envTemplate = `# GoBase Environment — generated by gobase init
APP_ENV=development
APP_PORT=8000
LOG_LEVEL=debug

# JWT
JWT_SECRET=change-me-to-a-64-char-random-hex-string-for-production
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d

# Database (PostgreSQL)
DB_HOST=localhost
DB_PORT=5432
DB_USER=gobase
DB_PASSWORD=gobase
DB_NAME=gobase
DB_SSLMODE=disable

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# MinIO / S3
MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_USE_SSL=false
MINIO_BUCKET=gobase

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# Email (optional — leave blank to disable verification emails)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=noreply@example.com

# OAuth2 (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
OAUTH_REDIRECT_URL=http://localhost:8000/auth/callback
`

const composeTemplate = `version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gobase
      POSTGRES_PASSWORD: gobase
      POSTGRES_DB: gobase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gobase"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
`

func runInit() {
	created := 0

	if _, err := os.Stat(".env"); os.IsNotExist(err) {
		if err := os.WriteFile(".env", []byte(envTemplate), 0600); err != nil {
			fatal("could not write .env: %v", err)
		}
		fmt.Println("created .env")
		created++
	} else {
		fmt.Println(".env already exists, skipping")
	}

	if _, err := os.Stat("docker-compose.yml"); os.IsNotExist(err) {
		if err := os.WriteFile("docker-compose.yml", []byte(composeTemplate), 0644); err != nil {
			fatal("could not write docker-compose.yml: %v", err)
		}
		fmt.Println("created docker-compose.yml")
		created++
	} else {
		fmt.Println("docker-compose.yml already exists, skipping")
	}

	if created > 0 {
		fmt.Println("\nNext steps:")
		fmt.Println("  1. Edit .env with your settings")
		fmt.Println("  2. gobase start")
		fmt.Println("  3. gobase migrate")
	}
}

// ── start / stop ──────────────────────────────────────────────────────────────

func runStart() {
	ensureComposeFile()
	fmt.Println("Starting GoBase stack...")
	if err := runCompose("up", "-d", "--remove-orphans"); err != nil {
		fatal("start failed: %v", err)
	}
	fmt.Println("\nStack is up. Waiting for services to become healthy...")
	waitForHealth(15, 2*time.Second)
}

func runStop() {
	ensureComposeFile()
	fmt.Println("Stopping GoBase stack...")
	if err := runCompose("down"); err != nil {
		fatal("stop failed: %v", err)
	}
	fmt.Println("Stack stopped.")
}

// ── status ────────────────────────────────────────────────────────────────────

type serviceCheck struct {
	name string
	url  string
}

var services = []serviceCheck{
	{"gateway", "http://localhost:8000/health"},
	{"auth", "http://localhost:8001/health"},
	{"rest", "http://localhost:8002/health"},
	{"realtime", "http://localhost:8003/health"},
	{"storage", "http://localhost:8004/health"},
	{"functions", "http://localhost:8005/health"},
}

func runStatus() {
	fmt.Printf("%-14s %-8s %s\n", "SERVICE", "STATUS", "LATENCY")
	fmt.Println(strings.Repeat("─", 40))

	client := &http.Client{Timeout: 3 * time.Second}
	allOK := true

	for _, svc := range services {
		start := time.Now()
		resp, err := client.Get(svc.url)
		elapsed := time.Since(start)

		if err != nil || resp.StatusCode != 200 {
			fmt.Printf("%-14s %-8s\n", svc.name, "down")
			allOK = false
		} else {
			fmt.Printf("%-14s %-8s %dms\n", svc.name, "up", elapsed.Milliseconds())
		}
		if resp != nil {
			resp.Body.Close()
		}
	}

	fmt.Println()
	if allOK {
		fmt.Println("All services healthy.")
	} else {
		fmt.Println("Some services are not responding. Run 'gobase logs' to investigate.")
		os.Exit(1)
	}
}

// ── logs ──────────────────────────────────────────────────────────────────────

func runLogs(service string) {
	ensureComposeFile()
	args := []string{"logs", "-f", "--tail=100"}
	if service != "" {
		args = append(args, service)
	}
	if err := runComposeInteractive(args...); err != nil {
		fatal("logs failed: %v", err)
	}
}

// ── migrate ───────────────────────────────────────────────────────────────────

func runMigrate() {
	binary, err := findBinary("migrate")
	if err != nil {
		fmt.Println("migrate binary not found in ./bin/; building it first...")
		build := exec.Command("go", "build", "-o", "bin/migrate", "./app/migrate")
		build.Stdout = os.Stdout
		build.Stderr = os.Stderr
		if err := build.Run(); err != nil {
			fatal("build failed: %v", err)
		}
		binary = "./bin/migrate"
	}

	fmt.Println("Running migrations...")
	cmd := exec.Command(binary)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fatal("migrations failed: %v", err)
	}
	fmt.Println("Migrations complete.")
}

// ── deploy ────────────────────────────────────────────────────────────────────

func runDeploy() {
	token := os.Getenv("GOBASE_TOKEN")
	if token == "" {
		fatal("GOBASE_TOKEN environment variable is not set.\nGet a token at https://gobase.dev/dashboard → Settings → API Keys")
	}

	projectID := os.Getenv("GOBASE_PROJECT_ID")
	if projectID == "" {
		fatal("GOBASE_PROJECT_ID environment variable is not set.")
	}

	cloudURL := envOrDefault("GOBASE_CLOUD_URL", "https://api.gobase.dev")
	url := fmt.Sprintf("%s/controlplane/v1/projects/%s/deploy", cloudURL, projectID)

	req, _ := http.NewRequest("POST", url, nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fatal("deploy request failed: %v", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)

	if resp.StatusCode >= 400 {
		var errResp map[string]interface{}
		_ = json.Unmarshal(body, &errResp)
		fatal("deploy failed (%d): %s", resp.StatusCode, body)
	}

	fmt.Printf("Deploy triggered for project %s\n", projectID)
	fmt.Println("Monitor at https://gobase.dev/dashboard")
}

// ── helpers ───────────────────────────────────────────────────────────────────

func runCompose(args ...string) error {
	cmd := exec.Command("docker", append([]string{"compose"}, args...)...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func runComposeInteractive(args ...string) error {
	cmd := exec.Command("docker", append([]string{"compose"}, args...)...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func ensureComposeFile() {
	if _, err := os.Stat("docker-compose.yml"); os.IsNotExist(err) {
		fatal("docker-compose.yml not found. Run 'gobase init' first.")
	}
}

func waitForHealth(attempts int, interval time.Duration) {
	client := &http.Client{Timeout: 2 * time.Second}
	for i := 0; i < attempts; i++ {
		ok := 0
		for _, svc := range services {
			resp, err := client.Get(svc.url)
			if err == nil && resp.StatusCode == 200 {
				ok++
				resp.Body.Close()
			}
		}
		if ok == len(services) {
			fmt.Printf("All %d services healthy.\n", ok)
			return
		}
		fmt.Printf("  %d/%d ready, retrying in %s...\n", ok, len(services), interval)
		time.Sleep(interval)
	}
	fmt.Println("Some services did not become healthy in time. Run 'gobase status' to check.")
}

func findBinary(name string) (string, error) {
	candidates := []string{
		filepath.Join("bin", name),
		filepath.Join(".", name),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("not found")
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}
