apiVersion: v1
kind: ConfigMap
metadata:
  name: gobase-config
  namespace: gobase
data:
  APP_ENV: "production"
  APP_PORT_GATEWAY:   "8000"
  APP_PORT_AUTH:      "8001"
  APP_PORT_REST:      "8002"
  APP_PORT_REALTIME:  "8003"
  APP_PORT_STORAGE:   "8004"
  APP_PORT_FUNCTIONS: "8005"

  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_USER: "gobase"
  DB_NAME: "gobase"

  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"

  MINIO_ENDPOINT:   "minio-svc:9000"
  MINIO_ACCESS_KEY: "gobase-minio"
  MINIO_USE_SSL:    "false"

  SMTP_HOST: "smtp.yourdomain.com"
  SMTP_PORT: "587"
  SMTP_USER: "noreply@yourdomain.com"
  SMTP_FROM: "GoBase <noreply@yourdomain.com>"
